### ISSUE TITLE
Why the merged commits don't appear in the history map as a branch orz

### ISSUE THREAD

**Issue by betairylia** [Fairy-Neko/miniRAID_melon#9]
SO UNHAPPY ( x
( How to make them appear in history tree ? e.g. github > Insights > Network
( SAD )

@higadjan 
( sry for so annoying lol

**Comment by YuzukiS** [comment]
(plz stop complaining and make it run(x

**Comment by betairylia** [comment]
TAT

**Comment by betairylia** [comment]
I disappeared again x
sad (

**Comment by betairylia** [comment]
One should not select "combine commits" when merging branches to have the complete history tree view.
